// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqswuibgnkdvrfocwjou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxc3d1aWJnbmtkdnJmb2N3am91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzc4OTIsImV4cCI6MjA3MTc1Mzg5Mn0.X0wAbifCxb9i_B1lHOlVVtFYyht1AreatERbYCaAf18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});